Add code back in to add relation between instance and code
ONSdigital/dp-dimension-importer pull request #39
Opened 2018-07-03 14:48 UTC by CarlHembrough

### What

Add code back in to add relation between instance and code

### How to review

Review changes

### Who can review

Anyone

2018-07-03 14:49 UTC, mattrout92 submitted a review, later dismissed

2018-07-03 14:50 UTC, mattrout92 commented
I wouldn't merge it yet though ;)

2018-07-17 11:02 UTC, nshumoogum requested changes

2018-07-17 11:02 UTC, nshumoogum commented on model/models.go
> +	URL string `json:"href"`
Should this not be HRef instead of URL (to be consistent with our other API's)?

2018-07-17 11:02 UTC, nshumoogum commented on repository/instance_repository.go
> +func (repo *InstanceRepository) CreateCodeRelationship(i *model.Instance, codeListId, code string) error {
Perhaps `codeListID` instead of `codesListId`?

2018-07-17 13:05 UTC, nshumoogum approved these changes

2018-07-19 14:05 UTC, merged